name = "SebTheCat Blog"
license = "Unlicensed"
description = "Blog theme for SebTheCat.com"
homepage = "https://sebthecat.com"
tags = ["bootstrap", "blog", "font awesome"]
features = ["responsive", "blog"]
min_version = 0.55

[author]
  name = "Brett Richardson"
  homepage = "https://sebthecat.com"

[original]
  name = "Alan Orth"
  homepage = "https://englishbulgaria.net"